### DISCUSSION TITLE
[FEATURE] Add "nav-header" items to vertical menu

### DISCUSSION THREAD

**Discussion by cavasinf** [tabler/tabler#1224] [Ideas]
When using vertical menu,
it will be nice if we can add "menu divider/spacer".

It can look something like that

![image](https://user-images.githubusercontent.com/25293190/145583659-55d6a06e-0e4c-49fe-bf15-e3e92f2d23fc.png)

**Comment by cavasinf** [comment]
Any update on this?

I've ended to create my own class `nav-divider`, 
that I place instead of `nav-item` when needed.

And then add this `scss`:
```scss
.navbar-vertical {
  .navbar-nav {
    .nav-divider {
      background-color: rgba(0, 0, 0, .1);

      .nav-link {
        &:hover, &:active, &:focus {
          color: inherit;
          cursor: default;
        }
      }
    }
  }
}
```

Result:

![image](https://user-images.githubusercontent.com/25293190/221904624-49e47798-71d5-4209-8078-c39de8e68506.png)


```html
<ul class="navbar-nav pt-lg-3">
   <li class="nav-divider  ">
      <a class="nav-link" href="#">
      <span class="nav-link-title">Divider 1</span>
      </a>
   </li>
   <li class="nav-item  ">
      <a class="nav-link" href="">
      <span class="nav-link-icon d-md-none d-lg-inline-block text-center"><i class="fas fa-calendar"></i></span>
      <span class="nav-link-title">1.11</span>
      </a>
   </li>
   <li class="nav-item  ">
      <a class="nav-link" href="">
      <span class="nav-link-icon d-md-none d-lg-inline-block text-center"><i class="fas fa-file-contract"></i></span>
      <span class="nav-link-title">1.2</span>
      </a>
   </li>
   <li class="nav-divider  ">
      <a class="nav-link" href="#">
      <span class="nav-link-title">Divider 2</span>
      </a>
   </li>
   <li class="nav-item  dropdown">
      <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" data-bs-auto-close="false" aria-expanded="1">
      <span class="nav-link-icon d-md-none d-lg-inline-block text-center"><i class="fas fa-paste"></i></span>
      <span class="nav-link-title">2.1</span>
      </a>
      <div class="dropdown-menu " data-bs-popper="none">
         ...
      </div>
   </li>
</ul>

```
