### ISSUE TITLE
table-hover with table-striped, the latter wins!

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#108]
If I use `table-hover` **OR** `table-striped` at single time they work!

But using both together doesn't: `table-striped` wins!

Why? Bug?

**Comment by rtd62** [comment]
Those are just standard Bootstrap classes and should work together... that's strange. Perhaps it's a bug?

**Comment by johnunclesam** [comment]
@rtd62 maybe in this code we need an `!important`. But I doubt this is correct.

```css
.table-hover tbody tr:hover {
  background-color: rgba(0, 0, 0, 0.04) !important;
}
```
