### ISSUE TITLE
[BUG] bg-*color* overwrites font-color

### ISSUE THREAD

**Issue by JustGreg** [tabler/tabler#1082]
**Describe the bug**

In [utils/_colors.scss](https://github.com/tabler/tabler/blob/main/src/scss/utils/_colors.scss) font-color is set to `#ffffff !important`.
Generated CSS would look like this:
```css
.bg-dark {
  color: #ffffff !important;
  background: #1e293b !important;
}
.text-dark {
  color: #1e293b !important;
}
.bg-white {
  color: #ffffff !important;
  background: #ffffff !important;
}
.text-white {
  color: #ffffff !important;
}
```

The following HTML-Code will display a white text on a white background:
```html
<div class="bg-white text-dark">text</div>
```
(this is because bg-white is declared after text-dark)

For some reason this part is missing in https://preview.tabler.io/dist/css/tabler.css
