### ISSUE TITLE
[BUG] Font customisation not working as instructed

### ISSUE THREAD

**Issue by Lombra** [tabler/tabler#1169]
**Describe the bug**

Font customisation as per [instructions](https://preview.tabler.io/docs/customize.html) are ineffective.

**Device**

 - Browser: Firefox 102
 - OS: Windows 10

**To reproduce**

Include the following style:

```css
body {
  --tblr-font-sans-serif: 'Inter';
}
```

Example of working style
```css
:root {
  --tblr-font-sans-serif: 'Inter' !important;
}
```
