### ISSUE TITLE
[FEATURE] Make dropdown toggling smooth and pleasant

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1323]
**Is your feature request related to a problem? Please describe.**
Not a problem. I was just thinking it could be nice if the dropdowns appeared a little more gracefully than just suddenly.

**Describe the solution you'd like**
I made this addition to my CSS:

```css
.dropdown-menu:not(.ts-dropdown),
.navbar-nav .dropdown-menu {
	position: absolute;
	display: block;
	visibility: hidden;
	transition: all .2s;
	top: 100%;
	left: 0;
	opacity: 0;
	transform: scale(0.75) translateY(-30px);
}
.dropdown-menu-end,
.navbar-nav .dropdown-menu-end {
	right: 0;
	left: auto;
}
.dropdown-menu.show {
	visibility: visible;
	opacity: 1;
	transform: scale(1) translateY(0em);
}

```

I tried to get a screen recording but I use Linux so of course the built-in screen capture tool isn't working, it was only capturing the first frame for the entire duration of the video. Sigh.

Instead, just navigate to the Tabler Preview site, open Devtools and go to the Style Editor tab and paste in that CSS, then click around some of the nav dropdowns and you'll see the effect.

Unfortunately, this does require that the dropdown parent is relatively positioned, and not static. I don't know what else this might break yet.

**Describe alternatives you've considered**
I can keep this in my CSS but I thought it might be worth considering for inclusion into the project. I don't know if it's the right fit/feel that you're going for, but for my project I quite like the effect.

(Edit: Slight CSS improvements, like compatibility with tomselect)
