### ISSUE TITLE
[BUG] Missing color variables usage

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1335]
**Describe the bug**

When redefining colors of tabler variables:
- `--tblr-primary`
- `--tblr-danger`
- ...

Some class color definition is not fully link to that:
1. `btn-ghost`
https://github.com/tabler/tabler/blob/e9f5df4f3be110257f071aa08b16fe58123de452/dist/css/tabler.css#L16013-L16029
2. `alert-xxx`
https://github.com/tabler/tabler/blob/e9f5df4f3be110257f071aa08b16fe58123de452/dist/css/tabler.css#L14561-L14583

**To reproduce**

1. Change color variable values
```css
:root {
  --tblr-font-sans-serif: Poppins, Arial, sans-serif;
  --tblr-dark: #1d273b;
  --tblr-primary: #a8f88c;
  --tblr-primary-darken: #273848;
  --tblr-primary-rgb: 168, 248, 140;
  --tblr-secondary: #009e94;
  --tblr-secondary-darken: #008f86;
  --tblr-secondary-rgb: 0, 158, 148;
  --tblr-success: #8e2fb3;
  --tblr-success-darken: #2eab42;
  --tblr-success-rgb: 142, 47, 179;
  --tblr-info: #0029ff;
  --tblr-info-darken: #4093d9;
  --tblr-info-rgb: 0, 41, 255;
  --tblr-warning: #a1b32f;
  --tblr-warning-darken: #ee6307;
  --tblr-warning-rgb: 161, 179, 47;
  --tblr-danger: #ee00ff;
  --tblr-danger-dark: #ce3838;
  --tblr-danger-rgb: 238, 0, 255;
  --tblr-body-color: #1d273b;
  --tblr-body-color-rgb: 29, 39, 59;
  --tblr-body-bg: #f1f5f9;
  --tblr-body-bg-rgb: 241, 245, 249;
  --tblr-border-color: #e6e7e9;
  --tblr-highlight-bg: #fdeccc;
  --tblr-link-color: #009e94;
}
```
2. Add button ghost
4. Add Alert
5. Sees default Tabler color

**Screenshots**

- btn-ghost
![image](https://user-images.githubusercontent.com/25293190/198022210-71304555-70ff-4e87-aa8e-e41a2ab4a2cf.png)

- alert-xxx
![image](https://user-images.githubusercontent.com/25293190/198022294-765b4c19-7b47-4319-864f-a4bba99c6498.png)
