### ISSUE TITLE
[BUG] .page-item-title does not work with .theme-dark

### ISSUE THREAD

**Issue by beginor** [tabler/tabler#1385]
`.page-item-title` is hardcoded to use color `#1d273b`, and it can not be seen in dark mode unless mouse hover it.

```css
.page-item-title {
    font-size: 1rem;
    font-weight: var(--tblr-font-weight-normal);
    color: #1d273b;
}
```

The color of `.page-item-title` should be the same as `.page-item-subtitle`

```css
.page-item-title {
    font-size: 1rem;
    font-weight: var(--tblr-font-weight-normal);
    color: var(--tblr-muted);
}
```

**Device**

 - All browsers.

**Screenshots**

![image](https://user-images.githubusercontent.com/159065/203744789-eb5d3009-a5f7-41ea-913e-e97ecb1854fe.png)

After override  the color value of `.page-item-title` to `color: var(--tblr-muted);`

![image](https://user-images.githubusercontent.com/159065/203745162-ee31ce97-ef2f-4413-ae13-b3c31f512dd8.png)
