### ISSUE TITLE
too few space between card-actions

### ISSUE THREAD

**Issue by nerdoc** [tabler/tabler#1410]
**Describe the bug**

when 2 or more card-actions are displayed, there is too few space between them, compared to the other elements in Tabler.
![grafik](https://user-images.githubusercontent.com/2955584/207040434-c8c802a5-e7f1-4afc-bd0d-46d436b03bbd.png)

I helped myself with a small fix:
```css
.list-group-item-actions {
    /* add a me-1 */
    margin-right: 0.25rem !important;
}
```
Now it looks better:
![grafik](https://user-images.githubusercontent.com/2955584/207040619-50918a9d-8dba-4769-b3ee-2e2816171e2f.png)

But this should be fixed in Tabler itself... Maybe even a me-2 could be better. An I think the last one doesn't need to have this - but you know better here, @codecalm.
