### ISSUE TITLE
[FEATURE]  - SERP views 

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1437]
if someone have time to include this in the project  more on: https://www.wordstream.com/serp

```html
<div id="google-serp" style="background-color:#fff;">
    <div style="display:block;"  class="google-title">google seo title</div>
    <cite style="display:block;"  class="google-url">seo_url..../cite>
    <div class="snippet-descr">
        <span class="preview-date">format("M d, Y") - </span>
        <span class="preview-descr">seo description</span>
    </div>
    <div class="preview-rating uk-flex uk-flex-middle">
        <img alt="Rating stars" width="65" style="margin-right: 6px;" src="...">
        Rating: 4.7/5 - 333 votes
     </div>
</div>
```

```css
 #google-serp{
    border: 1px solid #dddddd;
    max-width: 600px;
    padding: 15px;
    margin: 0 0 20px 0;
}

.google-title {
    color: #12C;
    font-family: arial, sans-serif;
    font-size: 20px;
    font-weight: 400;
    height: auto;
    line-height: 19px;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: none;
    margin-bottom: 10px;
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    padding: 0px;
    text-align: left;
    text-decoration: none;
    visibility: visible;
    width: auto;

}

.google-url {
    color: #093;
    display: block;
    font-family: arial, sans-serif;
    font-size: 14px;
    font-style: normal;
    font-weight: normal;
    height: auto;
    line-height: 16px;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: none;
    margin: 0px;
    padding: 0px;
    text-align: left;
    visibility: visible;
    max-width: 600px;
}

.google-desc {
    color: #222;
    font-family: arial, sans-serif;
    font-size: 13px;
    font-weight: normal;
    height: auto;
    line-height: 18.2px;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: none;
    margin-bottom: 0px;
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    padding-bottom: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    text-align: left;
    visibility: visible;
    max-width: 600px;
}
.preview-date, .preview-rating {
    color: #70757a;
    line-height: 1.58;
    font-size: 14px;
}
.uk-flex-middle {
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
}
.uk-flex {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
.uk-flex-middle {
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
}

.snippet-descr {
    color: #4d5156;
    font-size: 14px;
    line-height: 1.58;
    max-width: 600px;
}
```
