### ISSUE TITLE
[BUG] Alerts are transparent

### ISSUE THREAD

**Issue by born2discover** [tabler/tabler#1709]
It seems that in Beta20 alerts are incorrectly transparent.

That is, they lack a background-color as the variable referenced by `.alert` -> background-color is `--tblr-alert-bg`  which in turn is an alias to `--tblr-surface`. However the latter seems to have been omitted in Beta20.

```css
.alert {
--tblr-alert-bg: var(--tblr-surface);
(...)
background-color: var(--tblr-alert-bg);
}
```

I checked #1692 and the referenced #1684 but the latter does not seem to fix the issue with `--tblr-surface`.
