### ISSUE TITLE
[BUG] Dark mode, calendar picker daterange

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1974]
### Describe the bug

Simple datepicker works: https://preview.tabler.io/form-elements.html

But using the same picker with date-range mode has invalid colors:
<img width="327" alt="Bildschirmfoto 2024-10-10 um 23 03 29" src="https://github.com/user-attachments/assets/49a780e5-e1d6-4357-9394-8e7b5ddaec7d">

### Solution

My workaround for now is:

```css
[data-bs-theme=dark] {
    .litepicker .container__days .day-item.is-in-range {
        --litepicker-is-in-range-color: var(--tblr-primary-text-emphasis);
    }
}
```

Not ideal, but better readable:
<img width="328" alt="Bildschirmfoto 2024-10-10 um 23 45 22" src="https://github.com/user-attachments/assets/b0ab9fbd-61a4-4167-96f0-aabcb6c38f82">
