### ISSUE TITLE
[BUG] Scrollbars lost transparent background after updating to 1.1.1 from 1.0.0-beta20

### ISSUE THREAD

**Issue by XEonAX** [tabler/tabler#2259]
### Browser

Firefox 137.0

### OS

Mac OS 15.2

### Screen size

1920x1080

### Describe the bug

Scrollbar are very prominent looking, once I updated to 1.1.1

Before tabler.min.css
```css
* {
  scrollbar-color:rgba(var(--tblr-scrollbar-color,var(--tblr-body-color-rgb)),.16) transparent
}
```

After tabler.min.css
```css
* {
  scrollbar-color:rgba(var(--tblr-scrollbar-color,var(--tblr-body-color-rgb)),0.16)
}
```

### How to reproduce

1. Have a scrollable div
2. Notice scrollbar

### Screenshots

Before

![Image](https://github.com/user-attachments/assets/a1af9bb2-c959-434d-8641-270b1d2f84b9)

After

![Image](https://github.com/user-attachments/assets/eed9f1e4-b900-4a62-ab81-eeb2eee7a0e7)
