### ISSUE TITLE
[BUG] some colors are broken in v1.2.0

### ISSUE THREAD

**Issue by lovasoa** [tabler/tabler#2283]
### Describe the bug

Some color foreground color classes were broken with the update to v1.2.0.

#### v1.1.0 has

```css
.text-instagram-fg {
  color: var(--tblr-instagram-fg) !important;
}
```

![Image](https://github.com/user-attachments/assets/35334acb-c30b-485b-a8ac-a7c20afae94e)

#### but v1.2.0 has

```css
.text-instagram-fg {
  color: #e4405f !important;
}
```

![Image](https://github.com/user-attachments/assets/663d4180-06a0-4cd0-a428-0add0a8fae97)

### Consequence

This breaks existing sites that used these classes, since the background is now the exact same color as the foreground and the text becomes unreadable.

Initially reported in https://github.com/sqlpage/SQLPage/issues/892

### How to reproduce

1. Go to https://codepen.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-/pen/Qwwpjwj
2. Compare with https://codepen.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-/pen/KwwWdNg

## v1.2.0
![Image](https://github.com/user-attachments/assets/881a194b-db2f-42d0-977e-66dfc8032020)

## v1.1.0
![Image](https://github.com/user-attachments/assets/a4960f02-64bd-4058-aada-70f09ef739fa)

### JSFiddle

https://codepen.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-/pen/Qwwpjwj
