### ISSUE TITLE
[BUG] Unintentional Left Margin?

### ISSUE THREAD

**Issue by XEonAX** [tabler/tabler#2319]
### Browser

Firefox 137

### OS

Macos 15.2 (24C101

### Screen size

1920x1080

### Describe the bug

Update to Tabler 1.2.0

following css in tabler.min.css
```css
@media (min-width:992px) {
  :host,
  :root {
    margin-left:calc(100vw - 100%);
    margin-right:0
  }
}
```
introduces a gap on the left side of the page

### How to reproduce

refer above

### Screenshots

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/3d74b047-67a0-4af3-a0a2-c911fe90f79e" />
