### ISSUE TITLE
Colour input white checkbox

### ISSUE THREAD

**Issue by the-foreigner** [tabler/tabler#240]
White colour input check box the "white" tick is not visible.

**Comment by viditvarshney** [comment]
i can't understand Please elaborate @the-foreigner

**Comment by the-foreigner** [comment]
Both are ticked but you cannot see the tick on white background

![image](https://user-images.githubusercontent.com/8706488/51640699-22095500-1f5c-11e9-8c32-8b52decd1323.png)

**Comment by CoderSquirrel** [comment]
@the-foreigner as you can see in [Form Elements' Page](https://preview.tabler.io/form-elements.html ) there's no built in white checkbox
but i think it may be because of the color that the checkmark uses in the svg used for it.
can you provide a link of exemple so i may help you?

in advance i think that you'll problame have to add another svg with the mark filled as black only for the white checkbox

**Comment by CoderSquirrel** [comment]
or you can make in this way
```css
.colorinput-input:checked ~ .colorinput-color.bg-white::before {
background: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='%23000' d='M6.564.75l-3.59 3.612-1.538-1.55L0 4.26 2.974 7.25 8 2.193z'/%3E%3C/svg%3E") no-repeat center center/50% 50%;
}
```
