### ISSUE TITLE
[BUG] --tblr-card-cap-bg no longer applies to .card-header

### ISSUE THREAD

**Issue by rsyring** [tabler/tabler#2417]
### Browser

Firefox 138.0.4

### OS

Ubuntu 24.04

### Screen size

1920 x 1080

### Describe the bug

From tabler.css v1.3.2

```css
/* Line 4,636 */
.card-header {
  padding: var(--tblr-card-cap-padding-y) var(--tblr-card-cap-padding-x);
  margin-bottom: 0;
  color: var(--tblr-card-cap-color);
  background-color: var(--tblr-card-cap-bg);
  border-bottom: var(--tblr-card-border-width) solid var(--tblr-card-border-color);
}
...
/* Line 18,727 */
.card-header {
  color: inherit;
  display: flex;
  align-items: center;

 /* This next line overrides the variable --tblr-card-cap-bg used above. */
  background: transparent;
}
```

### How to reproduce

Just look at the CSS file.  Or, use a card with .card-header and look at the styles.

### Screenshots

![Image](https://github.com/user-attachments/assets/85c2f21f-6f1d-4a05-bec8-2be6fb231cca)
