### ISSUE TITLE
Remove form-required

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#575]
Replace:

```html
<span class="form-required"></span>
```

With

```scss
.form-label.required:after {
  content: " *";
  color: $red;
}
```

And then add a class `required` to the form-label. This makes it much easier to work with form generation libraries.
