### ISSUE TITLE
[BUG] Alert Close Icon within Modal

### ISSUE THREAD

**Issue by gryevns** [tabler/tabler#624]
When you render an alert within a modal the `close` classes clash impacting the alert icon.

**Device**

 - Browser [*]
 - OS: [*]

**To reproduce**

https://jsfiddle.net/1xejsv5w/

**Screenshots**

See jsfiddle above.

**Comment by danswiser** [comment]
As far as I can tell, the `alert-dismissible .close`  sass is in the parent [bootstrap](https://github.com/twbs/bootstrap/blob/83b49aa688e30f0d2af22110b94c7d8b3deffcf0/scss/_alert.scss#L29-L40) code.

The issue can be fixed (mostly) by simply adding a [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) between `alert-dismissible` and `.close` selectors in the compiled css which would override the `.modal-content .close` selector later in the compiled css.

```css
.alert-dismissible > .close {
  position: absolute;
  top: 0;
  right: 0;
  padding: 0.75rem 1.25rem;
  color: inherit;
}
```

However, I'm not sure where @codecalm would want this added.
