### ISSUE TITLE
[BUG] Nav not in full width

### ISSUE THREAD

**Issue by sooxt98** [tabler/tabler#634]
![image](https://user-images.githubusercontent.com/13378059/83360044-e59c0380-a3b0-11ea-9174-bf89e434e5f0.png)

The css is missing in Release 1.0.0-alpha.7 which causing the nav to collapse
``` css
.navbar-collapse & {
    flex-grow: 1;
}
```
