### ISSUE TITLE
Pinterest Style Grid for Cards

### ISSUE THREAD

**Issue by Marcolino92** [tabler/tabler#672]
Hi, how can you create a Pinterest-style grid for cards?

**Comment by MrNicodemuz** [comment]
Are you referring to masonry type of grid?

https://getbootstrap.com/docs/4.5/components/card/#card-columns

**Comment by Marcolino92** [comment]
Yes, right. I tried with **card-columns** but nothing.

**Comment by MrNicodemuz** [comment]
I tried and it seemed to work just fine.

As the doc suggests, remember to add the following CSS:
```
.card-columns {
    column-count: 3;
}
.card-columns .card {
    width: 100%;
    display: inline-block;
}
```

**Comment by Marcolino92** [comment]
Hi, thank you very much. However, I realize that it is not responsive, it shows 3 columns in each device.

**Comment by MrNicodemuz** [comment]
Did you read the docs? https://getbootstrap.com/docs/4.5/components/card/#card-columns

```css
.card-columns {
  @include media-breakpoint-only(lg) {
    column-count: 4;
  }
  @include media-breakpoint-only(xl) {
    column-count: 5;
  }
}
```
