### ISSUE TITLE
[BUG] - Tabler icons on overlap layout not working with normal layout

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#787]
Tabler-icons on overlap layout not working with normal layout - The color  on dark overlap  and normal layout header  / navigation  is different color / stroke 

i fix this  with suffix   to add on end 
```scss
.navbar-dark {
    .icon {
        stroke: #fff;
    }
    .dropdown-menu{
        .icon {
            stroke: #0b0d10;
        }
    }
}
```

**Comment by brylocode** [comment]
@nejcdev can you add screenshot this bug? because I would like to understand you perfectly

**Comment by nejcdev** [comment]
@brylocode  yeah sure   on  https://preview.tabler.io/layout-navbar-overlap.html   if you use same icons on this https://preview.tabler.io/   template    the icons are white and background on last template is white-ish too  so i need to make fix to not use two different icons for same menu 

navbar-dark  class 


```css
.navbar .navbar-nav .active>.nav-link, .navbar .navbar-nav .nav-link.active, .navbar .navbar-nav .nav-link.show, .navbar .navbar-nav .show>.nav-link {
    color: #232e3c;
}
```

```html
<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="5 12 3 12 12 3 21 12 19 12"></polyline><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path></svg>
```
```css
.navbar-dark .navbar-nav .nav-link {
    color: rgba(255,255,255,.7);
}
```
```html
<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><polyline points="5 12 3 12 12 3 21 12 19 12"></polyline><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path></svg>
```
