### ISSUE TITLE
Dropdown menu in rtl mode

### ISSUE THREAD

**Issue by houslegend** [tabler/tabler#801]
**Describe the bug**

Dropdown menu in rtl mode

**Device**

 - Browser [Chrome ]
 - OS: [ android ]

**To reproduce**

1. Go to ' https://preview.tabler.io/layout-rtl.html ' See error

**Screenshots**
![Screenshot_2021-02-10-10-22-29-87](https://user-images.githubusercontent.com/62902107/107490420-2710bf80-6b8a-11eb-90e5-8245665b01a5.jpg)

**Comment by kevinpapst** [comment]
@codecalm 

Can be fixed with:
```css
[dir="rtl"] .dropdown-menu-arrow.dropdown-menu-end:before {
    transform: rotate(45deg);
}
```

Until now I didn't even recognize this little arrow gimmick, after so many years of use.
As no other dropdowns have that arrow thingy, we could even discuss if it could be removed entirely.
