### ISSUE TITLE
[FEATURE] - table sticky thead

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#809]
Can be added something like that in the code ? 

```css
.table-sticky>thead>tr>th,
.table-sticky>thead>tr>td {
	background: #009688;
	color: #fff;
	top: 0px;
	position: sticky;
}
.table-height {
	height: 320px;
	display: block;
	overflow: scroll;
	width: 100%;
}

table {
	border-collapse: collapse;
	border-spacing: 0;
}

.table-bordered>thead>tr>th,
.table-bordered>tbody>tr>th,
.table-bordered>thead>tr>td,
.table-bordered>tbody>tr>td {
	border: 1px solid #ddd;
}
```

```html
 <div class="table-responsive table-height">
      <table class="table table-bordered table-striped table-hover table-sticky">
         <thead>
            <tr>
               <th class="text-center" rowspan="2"> Product</th>
               <th class="text-center" colspan="2"> Sellable</th>
            </tr>
         </thead>
         <tbody>
            <tr>
               <td class="text-left">INFOCUS-VISION3PRO-MNB-</td>
               <td class="text-left">620</td>
               <td class="text-left">68,19,380</td>
            </tr>
            <tr>
               <td class="text-left">MOTO-G5-FG-16GB</td>
               <td class="text-left">52</td>
            </tr>                
            <tr>
               <td class="text-left">MOTO-GPLUS4-BL-16GB</td>
               <td class="text-left">0</td>
            </tr>
         </tbody>
      </table>
   </div>
```
