### ISSUE TITLE
[FEATURE] - Add page-wrapper CSS for fixing footer position

### ISSUE THREAD

**Issue by robiokidenis** [tabler/tabler#859]
**the position of the footer is not in bottom, when the page-body is small, the solution can add the following css**
```css
.page-wrapper{
    position: absolute;
    min-height: 100%!important;   
    width: 100%;
}
```

**Before adding css**
![image](https://user-images.githubusercontent.com/22372509/118946262-65372f80-b980-11eb-8b54-9769b1d4147f.png)

**After adding css**
![image](https://user-images.githubusercontent.com/22372509/118946793-f1e1ed80-b980-11eb-9110-a6dfb5fee0f4.png)
