### ISSUE TITLE
[BUG] Dark mode issues

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#945]
**Describe the bug**

After integration of Tabler into a larger project I found several minor problems with the dark mode. Unfortunately I didn't add comments what exactly was the issue, but the rules are so simple that verification should be 
I fixed these issues with the following SASS:

```scss
@include dark-mode {
    .link-dark {
        color: $dark-mode-text;
    }
    .bg-gray, .bg-default {
        color: $dark;
    }
    pre {
        background-color: transparent;
    }
    .btn-close {
        color: $dark-mode-text;
    }
    /* list items */
    .text-body {
        color: $dark-mode-text!important;
    }
    .list-group-item {
        border-color: $border-color-dark-transparent;
    }
}
```

The text body will be fixed with #944 by @rjd22 

EDIT: if you tell me how you want to see PRs, I am happy to contribute them. I just know that it can be painful to get CSS changes as PRs, because it needs a full-rebuild on your end to review...
