### ISSUE TITLE
.dropdown-icon, middle, bottom, top or -1px.

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#95]
```css
.dropdown-icon {
  ...
  vertical-align: -1px;
}
```

I think this is a mistake. Because for example I'm using another icon system and I'm fine with, for example: `vertical-align: middle;`.

Am I wrong?
