### ISSUE TITLE
[BUG] - Print view the table is broken on next page colide th with td

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#957]
on the many pages the text and table colide into one

**Comment by kevinpapst** [comment]
Can you share a link, screenshot and/or details how to reproduce that?

**Comment by nejcdev** [comment]
yes there is some breaking point overlapping the header and footer from previous page

**Comment by nejcdev** [comment]
here is one example ![Screenshot]https://ibb.co/jwD39kG

**Comment by kevinpapst** [comment]
I am definitely not an expert on that topic, but AFAIK browsers/HTML is simply not made for multi page printing - especially when it comes to tables overlapping page boundaries. But I might be wrong here and someone else knows more.

**Comment by nejcdev** [comment]
There are some ways to fix it   i manage fix it in that way that text overlap the borders   

Something like  this
```css
thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }
```
