### ISSUE TITLE
[FEATURE] - show only on mobile or only on web

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#967]
Is possible to add something like this in tabler

```css
.only-on-mobile{
    display: none;
}

@media only screen and (max-width: 480px) {
    .only-on-mobile{
        display: block;
    }
}
```
